language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - "/home/travis/.phpenv/versions/5.4/bin/composer self-update"
  - "composer update --prefer-source"
script: vendor/bin/phpunit --bootstrap tests/bootstrap.php --coverage-text tests/Tests
notifications:
  email:
    - frank@francoisfaubert.com
