language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - "composer update"
script: vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Tests
notifications:
  email:
    - frank@francoisfaubert.com
