# Site settings
title: Strata
email: frank@francoisfaubert.com
description: >
  Strata gives you a stable development environment and a
  Model View Controller framework that allows you to organize your
  Wordpress code outside of the templating engine.
baseurl: ""
url: "http://www.strata-framework.com"
twitter_username: strataframework
github_username:  francoisfaubert
current_version: dev-master

# Build settings
markdown: kramdown
highlighter: rouge
