# Site settings
title: Strata
email: frank@francoisfaubert.com
description: > # this means to ignore newlines until "baseurl:"
  Strata gives you a stable development environment and a
  Model View Controller framework that allows you to organize your
  Wordpress code outside of the templating engine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://strata.francoisfaubert.com" # the base hostname & protocol for your site
twitter_username: francoisfaubert
github_username:  francoisfaubert
current_version: dev-master

# Build settings
markdown: kramdown
